konfuzio-ai/document-validation-ui

src/assets/scss/variables.scss
src/components/DocumentAnnotations/Annotation.vue
src/components/DocumentAnnotations/EmptyAnnotation.vue
src/components/DocumentAnnotations/Label.vue
src/components/DocumentPage/DocumentPage.vue
src/locales/de.json

Annotations were appearing on the document even if they had text;
Making changes on the annotations was sometimes getting the loading icon to appear on other annotations with same labels;
Sometimes the edited text was not appearing on the annotation but instead the placeholder was showing;

Fix a couple of issues with annotations

---

src/components/DocumentAnnotations/DocumentAnnotations.vue

Noticed there were errors because of 2 duplicated states

Removed duplicated states

---

.env.example
src/assets/images/CaretDownWhiteImg.vue
src/assets/scss/document_category.scss
src/assets/scss/new_annotation.scss
src/assets/scss/variables.scss
src/components/DocumentAnnotations/DocumentAnnotations.vue
src/components/DocumentPage/DocumentPage.vue
src/components/DocumentPage/NewAnnotation.vue
src/locales/de.json
src/locales/en.json
src/store/document.js

Popup for creating new annotations from the document.
Ticket 9409

New annotation popup

---

src/assets/scss/document_name.scss
src/assets/scss/document_top_bar.scss
src/components/DocumentDashboard.vue
src/components/DocumentTopBar/DocumentName.vue
src/components/DocumentTopBar/DocumentTopBar.vue
src/store/display.js

Increase width for filename input and added ellipsis in the middle to show the end of the filename.

Filename Size Increase

---

.env.example
package-lock.json
package.json
src/main.js

Fix Sentry Integration for checking app performance 

---

.env.example
README.md
docs/README.md
public/index.html
src/assets/scss/categorize_modal.scss
src/assets/scss/document_annotations.scss
src/assets/scss/document_dashboard.scss
src/assets/scss/document_viewport_modal.scss
src/assets/scss/variables.scss
src/components/App.vue
src/components/DocumentAnnotations/CategorizeModal.vue
src/components/DocumentAnnotations/DocumentAnnotations.vue
src/components/DocumentCategory.vue
src/components/DocumentError.vue
src/components/DocumentTopBar/DocumentCategory.vue
src/components/DocumentsList/DocumentsList.vue
src/components/NotOptimizedViewportModal.vue
src/locales/de.json
src/locales/en.json
src/main.js
src/store/category.js
src/store/document.js

Lot of refactor occurred in the category and document store. Now the category id is not needed on the environment variables.

Categorize Modal feature when a document is going to be reviewed

---

README.md
docs/README.md
public/index.html
src/api.js
src/components/App.vue
src/components/DocumentAnnotations/ActionButtons.vue
src/store/document.js
src/store/index.js
src/store/project.js

Also updated the documentation.

Implement project and user token html variables for easier partners integration

---

src/components/DocumentPage/DocumentPage.vue
src/components/DocumentPage/NewAnnotation.vue

Changed implementation when creating new Annotations. Not when editing.

Allow multiple entities to be selected.

---

src/components/DocumentAnnotations/CategorizeModal.vue
src/store/document.js

The name of the field changed in the endpoint

Changed field name for confirming category

---

src/assets/scss/document_page.scss
src/components/DocumentAnnotations/CategorizeModal.vue
src/components/DocumentPage/DocumentPage.vue
src/store/document.js

The block happens when the categorize modal is active

Added extra validation to block doc page actions

---

src/components/DocumentAnnotations/DocumentAnnotations.vue
src/store/document.js

Improved the validation for same Labels from null Annotation Sets

Fixed bug with empty Labels length

---

src/components/DocumentTopBar/DocumentTopBar.vue

To only show lef & right components conditionally

Moved condition to parent component in top bar

---

src/store/document.js

To update state without extra API call to get the updated missing Annotations

Improved store action

---

package-lock.json
package.json
src/assets/images/ServerImage.vue
src/main.js

Get a limited amount of thumbnails at the same time, and get more as needed. Similar approach to Document Pages.

Add lazy loading to document thumbnail images

---

src/assets/scss/document_dashboard.scss
src/assets/scss/document_toolbar.scss
src/assets/scss/scrolling_document.scss
src/components/DocumentAnnotations/MultiAnnotationTableOverlay.vue
src/components/DocumentAnnotations/index.js
src/components/DocumentDashboard.vue
src/components/DocumentPage/DocumentToolbar.vue
src/components/DocumentPage/ScrollingDocument.vue
src/components/DocumentPage/ScrollingPage.vue

Also, small bug fixes & refactors.

Limit Document Zoom to maximum 500%

---

src/components/DocumentAnnotations/AnnotationRow.vue
src/components/DocumentAnnotations/EmptyAnnotation.vue
src/store/document.js
tests/unit/DocumentAnnotations.spec.js

Fix issues when cancelling an empty annotation edit and start a new one

Refactor empty annotation content state

---

src/components/App.vue

This was overriding the env locale, only considering the locale prop.

Remove default in locale prop

---

src/components/DocumentAnnotations/AnnotationContent.vue
src/components/DocumentAnnotations/AnnotationRow.vue

- Not relying on contenteditable text content since it would not always work as expected
- Passing the Annotation text when calling createSpan for accurate results

Fixed remaining bug:

---

src/assets/scss/document_edit.scss
src/components/DocumentEdit/EditSidebar.vue

- position of automatic split information
- only switch from sidebar adds & removes spltiting suggestions

Fixed styles related to automatic splitting

---

src/components/DocumentAnnotations/AnnotationRow.vue
src/components/DocumentAnnotations/DocumentLabel.vue

Fixed error with changing newSidebarAnnotationSelected object

Reduced time to unfocus annotation

---

src/assets/scss/annotation_details.scss
src/components/DocumentAnnotations/AnnotationDetails.vue

- Only show user who created or approved if not public document
- Always show confidence level and description

Changes to Label tooltip

---

src/assets/scss/document_annotations.scss
src/components/DocumentAnnotations/AnnotationRow.vue
src/components/DocumentAnnotations/DocumentAnnotations.vue
src/components/DocumentPage/DocumentPage.vue
src/store/document.js
tests/unit/DocumentAnnotations.spec.js

By default all Label Sets are collapsed

Add Accordion to Label Sets

---

src/components/DocumentAnnotations/AnnotationSetActionButtons.vue
src/components/DocumentAnnotations/DocumentAnnotations.cy.js
src/components/DocumentAnnotations/DocumentAnnotations.vue
src/locales/de.json
src/locales/en.json
src/locales/es.json
tests/unit/DocumentAnnotations.spec.js

- New annotation set buttons when accordion is closed
- Open first annotation set by default
- Improve unit and cypress tests

Annotation set accordion design improvements

---

src/components/DocumentPage/DocumentPage.vue
src/store/document.js

Reverts konfuzio-ai/document-validation-ui#352

Revert "Implement label name on document annotation hover"

---

package-lock.json
package.json
src/assets/scss/document_annotations.scss
src/assets/scss/document_search_bar.scss
src/assets/scss/document_toolbar.scss
src/assets/scss/theme.scss
src/assets/scss/variables.scss
src/components/DocumentAnnotations/AnnotationActionButtons.vue
src/components/DocumentAnnotations/AnnotationRow.vue
src/components/DocumentAnnotations/DocumentAnnotations.vue
src/components/DocumentPage/DocumentPage.cy.js
src/components/DocumentPage/DocumentPage.vue
src/components/DocumentPage/DocumentToolbar.cy.js
src/components/DocumentPage/DocumentToolbar.vue
src/components/DocumentPage/NewAnnotation.vue
src/components/DocumentPage/ScrollingDocument.vue
src/components/DocumentPage/ScrollingPage.vue
src/components/DocumentPage/SearchBar.vue
src/icons.js
src/locales/de.json
src/locales/en.json
src/locales/es.json
src/store/display.js
src/store/document.js

With possibility to search for missing annotations

Search Document Feature

---

src/components/DocumentPage/EditAnnotation.vue
src/locales/de.json
src/locales/en.json
src/locales/es.json

- Fixed issues 
- Added hide button to hide the popup for choosing other spans
- Implemented new validations

Add new validations for edit ann popup and hide button

---

src/assets/scss/error_page.scss
src/assets/scss/theme.scss
src/components/App.vue
src/components/ErrorPage.vue
src/icons.js
src/store/display.js
src/store/document.js

It will appear if the document is not found or the authentication token is wrong

Implement Main page error

---

src/components/DocumentPage/BoxSelection.vue
src/components/DocumentPage/DocumentPage.vue
src/store/display.js
src/store/document.js
src/store/selection.js

https://git.konfuzio.com/konfuzio/objectives/-/issues/12542

Implement selection lasso feature in document for creating new annotations

---

docs/tutorials.md

Fix docs indentation which results in proper listing of the steps.

Fix docs indentation
